theme: jekyll-theme-hacker
title: This is the personal homepage Alpandi Pardede, Hokkaido University Student.
description: What you will find here are links to my bio and publications, and repositories related to the former!
plugins:
- jemoji
url: "https://alpandi.github.oi/"
personal information
name: Alpandi Edison Pardede
place/date of birth: Pematangsiantar, June 08 1999
citizenship: Indonesian
sex : Male
religion : Christian
education
2004-2005: Methodist kindergarten 
2005-2011: Methodist elementary school
2011-2014: State junior high school 4
2014:2017: State senior high school 3
2017-2022: Undergraduate, Faculty of Agriculture, Palangka Raya University
publications
thesis: study of c-organic inland peat on various land covers
https://e-journal.upr.ac.id/index.php/jpt-upr/article/download/4090/3089
